#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

REPO_URL="${ANOMFIN_WEBSITE_REPO:-https://github.com/AnomFIN/anomfin-website.git}"
BRANCH="${ANOMFIN_WEBSITE_BRANCH:-main}"
CACHE_DIR="${ANOMFIN_WEBSITE_CACHE:-${REPO_ROOT}/.cache/anomfin-website}"

SPARSE_PATHS=(
  "public/assets/css"
  "public/assets/js"
  "public/assets/fonts"
  "public/assets/img/brand"
)

function log() {
  echo "[sync-theme] $*"
}

function ensure_clone() {
  if [[ ! -d "${CACHE_DIR}/.git" ]];
  then
    log "Cloning ${REPO_URL} into ${CACHE_DIR}"
    rm -rf "${CACHE_DIR}"
    git clone --filter=blob:none --sparse "${REPO_URL}" "${CACHE_DIR}"
  fi

  git -C "${CACHE_DIR}" remote set-url origin "${REPO_URL}"
  git -C "${CACHE_DIR}" fetch origin "${BRANCH}" --depth=1
  git -C "${CACHE_DIR}" checkout "FETCH_HEAD"
  git -C "${CACHE_DIR}" sparse-checkout set "${SPARSE_PATHS[@]}"
}

function copy_assets() {
  declare -A MAP=(
    ["public/assets/css"]="public/css/theme"
    ["public/assets/js"]="public/js/theme"
    ["public/assets/fonts"]="public/fonts"
    ["public/assets/img/brand"]="public/img/brand"
  )

  for source in "${!MAP[@]}"; do
    local target="${REPO_ROOT}/${MAP[$source]}"
    mkdir -p "${target}"
    if [[ -d "${CACHE_DIR}/${source}" ]]; then
      log "Syncing ${source} -> ${MAP[$source]}"

      local -a rsync_opts=(
        -a
        --delete
        --prune-empty-dirs
        "${CACHE_DIR}/${source}/"
        "${target}/"
      )

      if [[ "${MAP[$source]}" == "public/img/brand" ]]; then
        rsync_opts=(
          -a
          --delete
          --prune-empty-dirs
          --exclude 'apple-touch-icon.svg'
          --exclude 'favicon-*.png'
          "${CACHE_DIR}/${source}/"
          "${target}/"
        )
      fi

      rsync "${rsync_opts[@]}"
    else
      log "Warning: ${source} missing from ${REPO_URL}"
    fi
  done
}

function build_theme_index() {
  local theme_dir="${REPO_ROOT}/public/css/theme"
  local index_file="${theme_dir}/theme-index.css"
  log "Building ${index_file}"
  {
    echo "/* Auto-generated by tools/sync-theme.sh — do not edit manually. */"
    while IFS= read -r css_file; do
      local rel_path="${css_file#${theme_dir}/}"
      [[ "${rel_path}" == "theme-index.css" ]] && continue
      printf "@import url('./%s');\n" "${rel_path}"
    done < <(find "${theme_dir}" -type f -name '*.css' -print | LC_ALL=C sort)
  } > "${index_file}"
}

function main() {
  mkdir -p "${CACHE_DIR}"
  ensure_clone
  copy_assets
  build_theme_index
  log "Design system sync complete."
}

main "$@"
